### ISSUE TITLE
Button not working on iPhone

### ISSUE THREAD

**Issue by malailama** [annapogorelova/ng2-go-top-button#5]
I integrated the button in my Angular app. It works fine on desktop however on mobile devices (specifically iPhone) the button does not work as expected. After clicking on the button, the window scrolls to top but is stuck in the same position. It does not scroll down.

**Comment by annapogorelova** [comment]
@malailama, Unfortunately, I have no possibility to test it on the iPhone. So if you are able to debug it on your side and find out what's the issue is, I would be very thankful. Or you can even create a pull-request and send it to me. The issue should be in this method https://github.com/annapogorelova/ng2-go-top-button/blob/master/src/go-top-button.component.ts#L178-L196 The window Y offset is not calculated properly in the Safari Mobile browser.

**Comment by justerror** [comment]
#7
